knp_paginator:
  page_range: 5                     # Nombre de pages affichées dans la barre de pagination
  default_options:
    page_name: page               # Nom du paramètre GET utilisé pour la pagination
    sort_field_name: sort         # Nom du paramètre GET utilisé pour le tri
    sort_direction_name: direction # Nom du paramètre GET utilisé pour la direction du tri
    distinct: true
    # Nécessaire si la requête utilise DISTINCT pour éviter des doublons dans la pagination
