security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                default_target_path: app_project_db_index
                always_use_default_target_path: false
            logout:
                path: app_logout
                target: app_login
            lazy: true
            stateless: false

    access_control:
        # Public access to freelancer public profiles
        - { path: ^/freelancer/\d+/public-profile$, roles: PUBLIC_ACCESS }

        # Secure access to freelancer private profile and edit routes
        - { path: ^/freelancer/profile$, roles: ROLE_FREELANCER }
        - { path: ^/freelancer/profile/edit$, roles: ROLE_FREELANCER }

        # Secure client profile and edit routes
        - { path: ^/client/profile$, roles: ROLE_CLIENT }
        - { path: ^/client/profile/edit$, roles: ROLE_CLIENT }

        # Secure admin section
        - { path: ^/dashboard, roles: ROLE_ADMIN }

        # Public pages
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/project/db, roles: PUBLIC_ACCESS }

        # Allow homepage for unauthenticated users
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/project/db, roles: PUBLIC_ACCESS } # Allow homepage for unauthenticated users
        - { path: ^/reponse/l, roles: ROLE_ADMIN }
        # Reclamation routes for freelancers to report client projects
        - { path: ^/reclamation/new/\d+$, roles: ROLE_FREELANCER }

        # Reclamation routes for clients to report freelancer offers
        - { path: ^/reclamation/new/commande/\d+$, roles: ROLE_CLIENT }

        # Admin access to reclamations management
        - { path: ^/reclamation(/.*)?$, roles: ROLE_ADMIN }

        # Freelancer private reclamations
        - { path: ^/freelancer/reclamations$, roles: ROLE_FREELANCER }

        # Client private reclamations
        - { path: ^/client/reclamations$, roles: ROLE_CLIENT }

        # Admin profiles and dashboard
        - { path: ^/admin(/\d+/profile|/dashboard.*)$, roles: ROLE_ADMIN }

