security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|js|images)/
            security: false

        main:
            security: false # Disable authentication temporarily

    access_control: []
