security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                default_target_path: app_project_db_index # Redirect after successful login
                always_use_default_target_path: false # Allow redirects to last visited pages
            logout:
                path: app_logout
                target: app_login # Redirect after logout
            lazy: true
            stateless: false

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/freelancer, roles: ROLE_FREELANCER }
        - { path: ^/, roles: PUBLIC_ACCESS }
        - { path: ^/project/db, roles: PUBLIC_ACCESS }# Allow homepage for unauthenticated users
